### ISSUE TITLE
sending and receiving data with node-web-bluetooth

### ISSUE THREAD

**Issue by thefakhreddin** [1oginov/bluetooth-terminal#20]
Hi. I'm working on a node project that needs to communicate (read and write) with a BLE hardware.
I couldn't figure out how to write a simple send/receive code with this package so I would be really appreciated if anyone could provide a simple sample code that:

1. Scan and look for a specific name of the BLE device like mlt-bT05 or HC-08
2. Connect to the device
3. Read data from the device
4. If received data was 'How are you doing?', then send 'I'm doing fine' back to the device.

thanks in adv.

**Comment by 1oginov** [comment]
This package is about Web Bluetooth API which is for **browsers**, you can take a look at showcase here https://github.com/1oginov/Web-Bluetooth-Terminal However you need to find a way to simulate Web Bluetooth API in Node.js what we discused about in #10
