### ISSUE TITLE
Gatt operation already in progress

### ISSUE THREAD

**Issue by sakulstra** [1oginov/bluetooth-terminal#7]
Hello, thanks for this library. I just gave it a quick test run and faced some problems :)
When writing a few commands in chain like:
```
terminal.send("test 1234").then(() => terminal.send("test 2345").then(() => terminal.send("test 3456"))
```
I get an "gatt operation already in progress" error.
I didn't have a deeper look at the code yet, but it seems like currently send doesn't actually wait till the characters are send to return the promise. Also I was wondering why sendDelay is needed at all couldn't we simply use the promise in https://github.com/1oginov/bluetooth-terminal/blob/master/src/BluetoothTerminal.js#L395 which is returned by writeValue https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValue to determine the "finished state"?

**Comment by sakulstra** [comment]
hay @1oginov, for now i have created a pretty hack solution which seems to work for my purposes
```
  send(data) {
    // Convert data to the string using global object.
    data = String(data || '');

    // Return rejected promise immediately if data is empty.
    if (!data) {
      return Promise.reject('Data must be not empty');
    }

    data += this._sendSeparator;

    // Split data to chunks by max characteristic value length.
    let chunks = this.constructor._splitByLength(data,
        this._maxCharacteristicValueLength);

    // Return rejected promise immediately if there is no connected device.
    if (!this._characteristic) {
      return Promise.reject('There is no connected device');
    }

    let promise = Promise.resolve();

    promise = promise.then(() => new Promise((resolve, reject) => {
      // Iterate over chunks if there are more than one of it.
      this._writeChunks(chunks, 0 , resolve, reject);
    }));

    return promise;
  }

  _writeChunks(chunks, index, resolve, reject){
    if(index < chunks.length) {
      this._writeToCharacteristic(this._characteristic, chunks[index]).then(() => {
        this._writeChunks(chunks, index+1, resolve, reject);
      }).catch((e) => reject(e))
    } else {
      resolve();
    }
  }

/**
   * Write to characteristic.
   * @param {Object} characteristic
   * @param {string} data
   * @private
   */
  _writeToCharacteristic(characteristic, data) {
    return characteristic.writeValue(new TextEncoder().encode(data));
  }
```

**Comment by 1oginov** [comment]
What's your hardware? Have you found anywhere that `writeValue()` promise is fulfilled on proper data receiving?

**Comment by sakulstra** [comment]
@1oginov sry didn't find time to continue work on this yet. I'm using this with an at-09 at 115200 baud - it seems like it. At least the problem was resolved.

**Comment by 1oginov** [comment]
Hey @sakulstra check out v1.3.0
